const SUPABASE_URL='https://neezdrbrakllosqicmip.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lZXpkcmJyYWtsbG9zcWljbWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk0MjQxODQsImV4cCI6MjEwNTAwMDE4NH0.Ck4tL4KlpYx6zgd8WzzU9e7Is2ddxGDsq-G_9NyYV0A';
async function verifyActivation(code){
  const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/check_activation`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({input_code:String(code||'').trim()})});
  if(!response.ok)throw new Error(`Activation server ${response.status}`);
  return (await response.json())===true;
}
const activationStore={get:async()=>globalThis.chrome?.storage?.local?new Promise(r=>chrome.storage.local.get(['activation'],x=>r(x.activation||null))):JSON.parse(localStorage.getItem('raghbat_activation')||'null'),set:async x=>globalThis.chrome?.storage?.local?new Promise(r=>chrome.storage.local.set({activation:x},r)):localStorage.setItem('raghbat_activation',JSON.stringify(x)),clear:async()=>globalThis.chrome?.storage?.local?new Promise(r=>chrome.storage.local.remove('activation',r)):localStorage.removeItem('raghbat_activation')};
function activationUI(){const root=document.createElement('section');root.id='activationGate';root.dir='rtl';root.innerHTML='<div class="activation-card"><div class="activation-mark">R</div><h2>تفعيل Raghbati DZ</h2><p>أدخل رمز التفعيل للمتابعة.</p><input id="activationCode" type="text" autocomplete="off" placeholder="رمز التفعيل"><button id="activationSubmit">تفعيل</button><button id="activationLogout" hidden>إعادة التحقق / تسجيل الخروج</button><div id="activationMessage"></div></div>';document.body.prepend(root);const style=document.createElement('style');style.textContent='#activationGate{position:fixed;inset:0;z-index:999999;background:#f5f2ea;display:grid;place-items:center;font-family:Cairo,Segoe UI,Tahoma,Arial}.activation-card{width:min(360px,calc(100% - 32px));padding:28px;background:#fffdf8;border:1px solid #e2d9bd;border-top:4px solid #b3873c;text-align:center;color:#182922}.activation-mark{margin:auto;width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#0f5c44;color:#f4ecd8;font-size:25px;font-weight:700}.activation-card h2{color:#0b4432}.activation-card input,.activation-card button{width:100%;padding:11px;margin-top:10px;border-radius:4px;font:13px Cairo,Segoe UI,Tahoma,Arial}.activation-card input{border:1px solid #e2d9bd;background:#fffdf8}.activation-card button{border:0;background:#0f5c44;color:#f4ecd8;font-weight:700;cursor:pointer}.activation-card button:disabled{opacity:.6}.activation-card #activationLogout{background:#f2ded8;color:#9c3b2e}.activation-card #activationMessage{min-height:24px;margin-top:12px;font-size:12px;color:#9c3b2e}';document.head.append(style);return root}
async function initActivation(){const protectedRoot=document.querySelector('main,.layout');const gate=activationUI();if(protectedRoot)protectedRoot.style.display='none';const input=gate.querySelector('#activationCode'),submit=gate.querySelector('#activationSubmit'),logout=gate.querySelector('#activationLogout'),message=gate.querySelector('#activationMessage');const showApp=()=>{gate.remove();if(protectedRoot)protectedRoot.style.display='';const b=document.createElement('button');b.textContent='إعادة التحقق / تسجيل الخروج';Object.assign(b.style,{position:'fixed',bottom:'10px',left:'10px',zIndex:999998,font:'11px Cairo,Tahoma',padding:'5px 8px',border:'1px solid #e2d9bd',borderRadius:'3px',background:'#fffdf8',color:'#9c3b2e',cursor:'pointer'});b.onclick=async()=>{await activationStore.clear();location.reload()};document.body.append(b)};const saved=await activationStore.get();if(saved?.activated){showApp();return}submit.onclick=async()=>{const code=input.value.trim();if(!code){message.textContent='أدخل رمز التفعيل';return}submit.disabled=true;submit.textContent='جارٍ التحقق...';message.textContent='';try{if(await verifyActivation(code)){await activationStore.set({activated:true,code,activatedAt:new Date().toISOString()});showApp()}else message.textContent='رمز التفعيل غير صحيح'}catch(e){message.textContent='تعذر التحقق، تأكد من الاتصال بالإنترنت'}finally{submit.disabled=false;submit.textContent='تفعيل'}};logout.onclick=async()=>{await activationStore.clear();location.reload()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initActivation);else initActivation();
